import { Box, Button, Divider, Typography, Paper } from "@mui/material";
import Head from "next/head";

import { useEffect, useState } from "react";
import CompetitionClock from "../components/CompetitionClock";
import ElevatorView from "../components/ElevatorView";
import TeamScore from "../components/TeamScore";
import useTimer from "../hooks/useTimer";
import scoringService from "../lib/scoring";
import { client } from "../lib/supabase";

export default function Home() {
  const [red, setRed] = useState({});
  const [blue, setBlue] = useState({});
  const [update, setUpdate] = useState(null);

  const [timer, start, toggle, reset, paused, started] = useTimer();

  useEffect(() => {
    getTeams();

    setTimeout(() => {
      client
        .from("points")
        .on("UPDATE", (v) => {
          setUpdate(v.new);
        })
        .subscribe();
    }, 1000);

    return () => {
      client.removeAllSubscriptions().then(() => {
        console.log("Removed all subscriptions");
      });
    };
  }, []);

  useEffect(() => {
    if (update) {
      updateTeam(update);
      setUpdate(null);
    }
  }, [update]);

  useEffect(() => {
    const eventListener = (event) => {
      const code = event.code;

      if (code === "KeyR") {
        reset();
      } else if (code === "Enter" && !started) {
        start();
      } else if (code === "Space" && started) {
        event.preventDefault();
        toggle();
      }
    };

    document.addEventListener("keydown", eventListener);

    return () => {
      document.removeEventListener("keydown", eventListener);
    };
  });

  const getTeams = () => {
    client
      .from("points")
      .select("*")
      .then(({ data, error }) => {
        if (!error) {
          for (let team in data) {
            updateTeam(data[team]);
          }
        }
      });
  };

  const updateTeam = (updated) => {
    if (updated.team === "red") {
      setRed(updated);
    } else if (updated.team === "blue") {
      setBlue(updated);
    }
  };

  const getLead = () => {
    if (!(red && blue) || red.points === blue.points) {
      return "tie";
    } else if (red.points > blue.points) {
      return "red";
    } else {
      return "blue";
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx global>{`
        body {
          background: #121212;
        }
      `}</style>

      <Box>
        <CompetitionClock
          currentState={"Autonomous"}
          lead={getLead()}
          timer={timer}
          isWinnerFinal={false}
        />
        <Divider></Divider>
        <Box
          sx={{
            display: "flex",
            "& > :not(style)": {
              m: 1,
              width: 1280,
              height: 400,
            },
          }}
        >
          <TeamScore name="Blue" team={blue} />
          <TeamScore name="Red" team={red} />
        </Box>
      </Box>
    </div>
  );
}
